### ISSUE TITLE
Add multistream guide

### ISSUE THREAD

**Issue by jwoertink** [joysticktv/joysticktv.github.io#6]
Since we allow you to stream on multiple sites at the same time, we should add guides on how to setup multistreaming. It's different for each software which will make it a little tricky...

* OBS - install plugin
* Streammaster - comes with the OBS multistreamplugin by detault
* Streamlabs - You need to sign up for "ultra"
* Splitcam - I've never used it, but as I understand, it's built in
* XSplit - no clue...

**Comment by russ** [comment]
This is the OBS plugin mentioned above that needs to be installed. https://github.com/sorayuki/obs-multi-rtmp
